'use client'

import { useState } from 'react'
import { FileUpload } from '@/components/FileUpload'
import { ResumeComparison } from '@/components/ResumeComparison'
import { ScoreCard } from '@/components/ScoreCard'
import { RoleMatches } from '@/components/RoleMatches'
import { PDFHighlightViewer } from '@/components/PDFHighlightViewer'
import { IssueSummaryPanel } from '@/components/IssueSummaryPanel'
import { QuickRecommendations } from '@/components/QuickRecommendations'
import { ATSDiagnostic } from '@/components/ATSDiagnostic'
import { resumeApi } from '@/lib/api'
// TODO: Re-enable for later development
// import { SkillSuggestions } from '@/components/SkillSuggestions'
import { FileText, Target, Lightbulb, Upload, Eye, AlertCircle, Zap, MessageSquare, Briefcase, ChevronLeft, ChevronRight } from 'lucide-react'

type AnalysisView = 'overview' | 'fixes' | 'roles'

export default function Home() {
  const [resumeId, setResumeId] = useState<number | null>(null)
  const [scoreData, setScoreData] = useState<any>(null)
  const [roleMatches, setRoleMatches] = useState<any[]>([])
  const [activeTab, setActiveTab] = useState<'upload' | 'analyze'>('upload')
  const [activeView, setActiveView] = useState<AnalysisView>('overview')
  const [sectionAnalysis, setSectionAnalysis] = useState<any>(null)
  const [aiPanelOpen, setAiPanelOpen] = useState<boolean>(true) // AI panel open by default
  const [scrollToIssueId, setScrollToIssueId] = useState<string | null>(null) // For fix mode navigation
  const [autoGeneratedExplanation, setAutoGeneratedExplanation] = useState<any>(null) // Auto-generated AI explanation
  const [loadingExplanation, setLoadingExplanation] = useState<boolean>(false) // Loading state for auto-explanation

  const handleUploadSuccess = (id: number) => {
    setResumeId(id)
    setActiveTab('analyze')
    setActiveView('overview') // Start with overview (format + comparison)
  }

  const handleScoreReceived = (data: any) => {
    console.log('Score data received:', data)
    console.log('Recommendations:', data?.recommendations)
    setScoreData(data)
  }

  const handleRoleMatchesReceived = (matches: any[]) => {
    setRoleMatches(matches)
  }

  const handleSectionAnalyzed = (analysis: any) => {
    // Merge section analysis highlights with existing scoreData highlights
    setSectionAnalysis(analysis)
    if (analysis.highlights && analysis.highlights.length > 0) {
      setScoreData((prev: any) => ({
        ...prev,
        highlights: [...(prev?.highlights || []), ...analysis.highlights]
      }))
    }
  }

  return (
    <main className="min-h-screen">
      {/* Header */}
      <header className="bg-white shadow-sm border-b">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-3">
              <FileText className="h-8 w-8 text-primary-600" />
              <h1 className="text-3xl font-bold text-gray-900">Resume Tool</h1>
            </div>
            <div className="flex items-center space-x-4">
              <button
                onClick={() => setActiveTab('upload')}
                className={`flex items-center space-x-2 px-4 py-2 rounded-lg transition-colors ${
                  activeTab === 'upload'
                    ? 'bg-primary-600 text-white'
                    : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                }`}
              >
                <Upload className="h-4 w-4" />
                <span>Upload</span>
              </button>
              {resumeId && (
                <button
                  onClick={() => setActiveTab('analyze')}
                  className={`flex items-center space-x-2 px-4 py-2 rounded-lg transition-colors ${
                    activeTab === 'analyze'
                      ? 'bg-primary-600 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  <Target className="h-4 w-4" />
                  <span>Analyze</span>
                </button>
              )}
            </div>
          </div>
        </div>
      </header>

      {/* Main Content */}
      {activeTab === 'upload' && (
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="space-y-8">
            {/* Hero Section */}
            <div className="text-center space-y-4">
              <h2 className="text-4xl font-bold text-gray-900">
                Analyze Your Resume
              </h2>
              <p className="text-xl text-gray-600 max-w-2xl mx-auto">
                Get instant ATS compatibility scores and role matches for your resume
              </p>
            </div>

            {/* Features */}
            <div className="grid md:grid-cols-2 gap-6 mb-12">
              <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                <div className="flex items-center space-x-3 mb-3">
                  <div className="p-2 bg-primary-100 rounded-lg">
                    <FileText className="h-6 w-6 text-primary-600" />
                  </div>
                  <h3 className="font-semibold text-lg">Visual ATS Analysis</h3>
                </div>
                <p className="text-gray-600">
                  See formatting issues highlighted directly on your PDF with actionable fixes
                </p>
              </div>

              <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                <div className="flex items-center space-x-3 mb-3">
                  <div className="p-2 bg-primary-100 rounded-lg">
                    <Target className="h-6 w-6 text-primary-600" />
                  </div>
                  <h3 className="font-semibold text-lg">Role Matching</h3>
                </div>
                <p className="text-gray-600">
                  Discover which roles best match your experience and skills
                </p>
              </div>

              {/* TODO: Re-enable for later development */}
              {/* <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-200">
                <div className="flex items-center space-x-3 mb-3">
                  <div className="p-2 bg-primary-100 rounded-lg">
                    <Lightbulb className="h-6 w-6 text-primary-600" />
                  </div>
                  <h3 className="font-semibold text-lg">Skill Suggestions</h3>
                </div>
                <p className="text-gray-600">
                  Get personalized suggestions to improve your resume for target roles
                </p>
              </div> */}
            </div>

            {/* Upload Component */}
            <FileUpload onUploadSuccess={handleUploadSuccess} />
          </div>
        </div>
      )}

      {activeTab === 'analyze' && resumeId && (
        <div className="flex gap-0">
          {/* Left Sidebar Navigation - Aligned to left edge */}
          <aside className="w-56 flex-shrink-0 pl-4 pr-4">
            <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-4 sticky top-8">
              <h3 className="text-sm font-semibold text-gray-500 uppercase tracking-wider mb-4">
                Analysis Views
              </h3>
              <nav className="space-y-1">
                <button
                  onClick={() => setActiveView('overview')}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${
                    activeView === 'overview'
                      ? 'bg-blue-50 text-blue-700 border border-blue-200'
                      : 'text-gray-700 hover:bg-gray-50'
                  }`}
                >
                  <Eye className={`h-5 w-5 ${activeView === 'overview' ? 'text-blue-600' : 'text-gray-400'}`} />
                  <span className="font-medium">Overview</span>
                </button>

                <button
                  onClick={() => setActiveView('fixes')}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${
                    activeView === 'fixes'
                      ? 'bg-blue-50 text-blue-700 border border-blue-200'
                      : 'text-gray-700 hover:bg-gray-50'
                  }`}
                >
                  <Zap className={`h-5 w-5 ${activeView === 'fixes' ? 'text-blue-600' : 'text-gray-400'}`} />
                  <span className="font-medium">Quick Fixes</span>
                  {scoreData?.recommendations?.length > 0 && (
                    <span className="ml-auto bg-blue-600 text-white text-xs px-2 py-0.5 rounded-full">
                      {scoreData.recommendations.length}
                    </span>
                  )}
                </button>

                <button
                  onClick={() => setActiveView('roles')}
                  className={`w-full flex items-center gap-3 px-4 py-3 rounded-lg text-left transition-colors ${
                    activeView === 'roles'
                      ? 'bg-blue-50 text-blue-700 border border-blue-200'
                      : 'text-gray-700 hover:bg-gray-50'
                  }`}
                >
                  <Briefcase className={`h-5 w-5 ${activeView === 'roles' ? 'text-blue-600' : 'text-gray-400'}`} />
                  <span className="font-medium">Role Matches</span>
                  {roleMatches.length > 0 && (
                    <span className="ml-auto bg-blue-600 text-white text-xs px-2 py-0.5 rounded-full">
                      {roleMatches.length}
                    </span>
                  )}
                </button>
              </nav>
            </div>
          </aside>

          {/* Main Content Area - Uses remaining space with proper padding */}
          <div className="flex-1 min-w-0 py-8 pr-4 sm:pr-6 lg:pr-8">
            {/* Hidden: Score Overview - Trigger scoring but don't display */}
            <div className="hidden">
              <ScoreCard
                resumeId={resumeId}
                onScoreReceived={handleScoreReceived}
              />
            </div>

            {/* Overview View - Format Issues + Resume Comparison Combined */}
            {activeView === 'overview' && (
              <div className="space-y-8">
                    {/* Resume Comparison Section */}
                    <div>
                      <h2 className="text-xl font-semibold text-gray-900 mb-4">Resume vs ATS View</h2>
                      <ResumeComparison
                        resumeId={resumeId}
                        scoreData={scoreData}
                      />
                    </div>

                    {/* Format Issues Section */}
                    {scoreData?.issue_summary ? (
                      <div>
                        <h2 className="text-xl font-semibold text-gray-900 mb-4">Format Issues & Highlights</h2>
                        <div className="grid lg:grid-cols-3 gap-6">
                          {/* PDF with color-coded highlights (2 columns) */}
                          <div className="lg:col-span-2">
                            <PDFHighlightViewer
                              pdfUrl={`http://localhost:8000/api/resume/${resumeId}/file`}
                              highlights={scoreData.highlights || []}
                              resumeId={resumeId}
                              scrollToIssueId={scrollToIssueId}
                              onScrollComplete={() => setScrollToIssueId(null)} // Reset after scroll
                            />
                          </div>

                          {/* Right sidebar: Issue Summary (1 column) */}
                          <div className="lg:col-span-1">
                            <IssueSummaryPanel
                              summary={scoreData.issue_summary}
                              suggestions={[]}
                              issues={scoreData.issues || []}
                              issueDetails={scoreData.highlights?.map((h: any) => {
                                // If blocks array is empty but bbox exists, create a block from bbox
                                let blocks = h.blocks || []
                                if (blocks.length === 0 && h.bbox && Array.isArray(h.bbox) && h.bbox.length === 4) {
                                  blocks = [{
                                    page: h.page || 1,
                                    bbox: h.bbox,
                                    text_preview: h.message || h.tooltip || ''
                                  }]
                                }
                                
                                return {
                                  code: h.issue_id || h.issue_type || h.code || '',
                                  message: h.message || h.tooltip || '',
                                  severity: h.severity || 'medium',
                                  blocks: blocks,
                                  detected_reason: h.detected_reason || '',
                                  expected_section: h.expected_section || ''
                                }
                              }).filter((d: any) => d.code) || []}
                              onIssueClick={async (issueId) => {
                                setScrollToIssueId(issueId)
                                
                                // Open AI panel immediately when issue is clicked
                                setAiPanelOpen(true)
                                
                                // Auto-generate AI explanation for the clicked issue
                                const issueDetail = scoreData.highlights?.find((h: any) => 
                                  (h.issue_id || h.issue_type || h.code) === issueId
                                )
                                
                                if (issueDetail && resumeId) {
                                  // Generate intelligent prompt from issue data
                                  let prompt = issueDetail.message || issueDetail.tooltip || ''
                                  
                                  // Enhance prompt with block context if available
                                  if (issueDetail.blocks && issueDetail.blocks.length > 0) {
                                    const firstBlock = issueDetail.blocks[0]
                                    if (firstBlock.text_preview) {
                                      prompt = `${prompt} The text "${firstBlock.text_preview.substring(0, 100)}" was not properly extracted.`
                                    }
                                  }
                                  
                                  // Add detected reason if available
                                  if (issueDetail.detected_reason) {
                                    prompt = `${prompt} This was detected because: ${issueDetail.detected_reason}.`
                                  }
                                  
                                  // Add expected section if available
                                  if (issueDetail.expected_section) {
                                    prompt = `${prompt} This content should be in the ${issueDetail.expected_section} section.`
                                  }
                                  
                                  // Auto-generate explanation
                                  setLoadingExplanation(true)
                                  setAutoGeneratedExplanation(null)
                                  
                                  try {
                                    const response = await resumeApi.getDiagnostic(resumeId, prompt)
                                    setAutoGeneratedExplanation(response.data)
                                  } catch (error: any) {
                                    console.error('Failed to generate auto-explanation:', error)
                                    // Don't show error to user, just log it
                                  } finally {
                                    setLoadingExplanation(false)
                                  }
                                }
                              }}
                            />
                          </div>
                        </div>
                      </div>
                    ) : (
                      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-12 text-center">
                        <AlertCircle className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                        <h3 className="text-lg font-semibold text-gray-900 mb-2">No Format Issues Detected Yet</h3>
                        <p className="text-gray-600">Analysis is in progress. Please wait a moment...</p>
                      </div>
                    )}
                  </div>
                )}

            {/* Quick Fixes View */}
            {activeView === 'fixes' && (
              <div className="space-y-6">
                    {scoreData?.recommendations && scoreData.recommendations.length > 0 ? (
                      <QuickRecommendations
                        recommendations={scoreData.recommendations}
                        issueCount={scoreData.issue_summary?.total_issues || 0}
                      />
                    ) : (
                      <div className="bg-white rounded-xl shadow-sm border border-gray-200 p-12 text-center">
                        <Zap className="h-12 w-12 text-gray-400 mx-auto mb-4" />
                        <h3 className="text-lg font-semibold text-gray-900 mb-2">No Quick Fixes Available</h3>
                        <p className="text-gray-600">Complete the analysis to see recommendations.</p>
                      </div>
                    )}
                  </div>
                )}

            {/* Role Matches View */}
            {activeView === 'roles' && (
              <RoleMatches
                resumeId={resumeId}
                onMatchesReceived={handleRoleMatchesReceived}
              />
            )}
          </div>

          {/* Right Side AI Assistant Panel - Overlay (Fixed Position) */}
          <div
            className={`fixed top-16 right-0 bottom-0 flex flex-col bg-white border-l border-gray-200 shadow-2xl transition-transform duration-300 z-50 ${
              aiPanelOpen ? 'translate-x-0' : 'translate-x-full'
            }`}
            style={{ width: '384px' }}
          >
            {/* Panel Header */}
            <div className="flex items-center justify-between p-4 border-b border-gray-200 bg-gray-50 flex-shrink-0">
              <div className="flex items-center gap-2">
                <MessageSquare className="h-5 w-5 text-blue-600" />
                <h3 className="font-semibold text-gray-900">AI Assistant</h3>
              </div>
              <button
                onClick={() => setAiPanelOpen(false)}
                className="p-1 hover:bg-gray-200 rounded transition-colors"
                aria-label="Collapse AI Assistant"
              >
                <ChevronRight className="h-5 w-5 text-gray-600" />
              </button>
            </div>

            {/* Panel Content */}
            <div className="flex-1 overflow-y-auto">
              <ATSDiagnostic 
                resumeId={resumeId}
                autoGeneratedExplanation={autoGeneratedExplanation}
                loadingExplanation={loadingExplanation}
                onClearAutoExplanation={() => setAutoGeneratedExplanation(null)}
              />
            </div>
          </div>

          {/* Toggle Button (when panel is closed) - Fixed Position */}
          {!aiPanelOpen && (
            <button
              onClick={() => setAiPanelOpen(true)}
              className="fixed right-0 top-1/2 -translate-y-1/2 bg-blue-600 text-white p-3 rounded-l-lg shadow-lg hover:bg-blue-700 transition-colors z-40"
              aria-label="Open AI Assistant"
            >
              <ChevronLeft className="h-5 w-5" />
            </button>
          )}
        </div>
        )}
    </main>
  )
}

